## Predicting absenteeism using logistic regression 

#### Import libraries :

In [1]:
import pandas as pd
import numpy as np

#### Load data :

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed_data.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

#### Create targets :

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [6]:
targets.sum() / targets.shape[0] #45-55 balance roughly

0.45571428571428574

In [7]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)
data_with_targets is data_preprocessed
#checkpoint.

False

#### Select inputs for regression :

In [8]:
data_with_targets.shape

(700, 15)

In [9]:
data_with_targets.iloc[:,0:14]
#or 
#data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
..        ...       ...       ...       ...          ...              ...   
670         0         0         0         1            4                1   
671         0         0         1         0            4                3   
672         1         0         0         0            4                3   
673         0         0         0         1            4                4   
674         0         0         0         1            7                3   
675         0         0         1         0            9                2   
676         0         0         0         1            9                2   
677         1         0         0         0            9                2   
678         0         0         0         1            9                2   
679         1         0         0         0           10                4   
680         0         0         0         1           10                4   
681         1         0         0         0           10                4   
682         0         0         1         0           11                0   
683         0         0         0         1           11                0   
684         0         0         0         1           11                0   
685         0         0         0         1            5                0   
686         1         0         0         0            5                1   
687         0         0         0         1            5                1   
688         0         0         0         0            5                1   
689         0         0         0         1            5                2   
6

In [10]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

#### Standardize data :

In [11]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [12]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs.shape

(700, 14)

#### Split into T-T datasets :

In [14]:
from sklearn.model_selection import train_test_split

#### Split :

In [15]:
train_test_split(scaled_inputs,targets)

[array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976]]),
 array([[ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ...,  

In [16]:
x_train , x_test , y_train , y_test = train_test_split(scaled_inputs,targets, train_size=0.8, random_state = 20)

C:\Users\kiit1\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [17]:
print (x_test.shape,y_test.shape)

(140, 14) (140,)


In [18]:
print (x_train.shape,y_train.shape)

(560, 14) (560,)


##  Logistic regression Modelling 

#### Import libraries :

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

#### Training the model :

In [20]:
reg = LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
reg.score(x_train,y_train)

0.7803571428571429

#### Manually check accuracy :

In [22]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [23]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [24]:
np.sum(model_outputs==y_train)

437

In [25]:
model_outputs.shape[0]

560

In [26]:
score = np.sum(model_outputs==y_train) / model_outputs.shape[0]
score

0.7803571428571429

#### Finding intercepts and coefficients :

In [27]:
reg.intercept_

array([-0.20908973])

In [28]:
reg.coef_

array([[ 2.07044024,  0.33037751,  1.56321412,  1.31103462,  0.02578678,
        -0.08632909,  0.7233164 , -0.06154754, -0.20633005, -0.02869987,
         0.32595295, -0.1615189 ,  0.38151211, -0.32141202]])

In [29]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [30]:
summary_table = pd.DataFrame(columns = ['Feature Name'],data=feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature Name  Coefficient
0                  Reason_1     2.070440
1                  Reason_2     0.330378
2                  Reason_3     1.563214
3                  Reason_4     1.311035
4               Month Value     0.025787
5           Day of the week    -0.086329
6    Transportation Expense     0.723316
7          Distance to Work    -0.061548
8                       Age    -0.206330
9   Daily Work Load Average    -0.028700
10          Body Mass Index     0.325953
11                Education    -0.161519
12                 Children     0.381512
13                     Pets    -0.321412

In [31]:
summary_table.index=summary_table.index+1

summary_table.loc[0] = ['Intercept' , reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                 Intercept    -0.209090
1                  Reason_1     2.070440
2                  Reason_2     0.330378
3                  Reason_3     1.563214
4                  Reason_4     1.311035
5               Month Value     0.025787
6           Day of the week    -0.086329
7    Transportation Expense     0.723316
8          Distance to Work    -0.061548
9                       Age    -0.206330
10  Daily Work Load Average    -0.028700
11          Body Mass Index     0.325953
12                Education    -0.161519
13                 Children     0.381512
14                     Pets    -0.321412

#### Interpreting coefficients :

In [32]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds_ratio
0                 Intercept    -0.209090    0.811322
1                  Reason_1     2.070440    7.928313
2                  Reason_2     0.330378    1.391493
3                  Reason_3     1.563214    4.774141
4                  Reason_4     1.311035    3.710010
5               Month Value     0.025787    1.026122
6           Day of the week    -0.086329    0.917292
7    Transportation Expense     0.723316    2.061258
8          Distance to Work    -0.061548    0.940308
9                       Age    -0.206330    0.813565
10  Daily Work Load Average    -0.028700    0.971708
11          Body Mass Index     0.325953    1.385350
12                Education    -0.161519    0.850850
13                 Children     0.381512    1.464497
14                     Pets    -0.321412    0.725124

In [34]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature Name  Coefficient  Odds_ratio
1                  Reason_1     2.070440    7.928313
3                  Reason_3     1.563214    4.774141
4                  Reason_4     1.311035    3.710010
7    Transportation Expense     0.723316    2.061258
13                 Children     0.381512    1.464497
2                  Reason_2     0.330378    1.391493
11          Body Mass Index     0.325953    1.385350
5               Month Value     0.025787    1.026122
10  Daily Work Load Average    -0.028700    0.971708
8          Distance to Work    -0.061548    0.940308
6           Day of the week    -0.086329    0.917292
12                Education    -0.161519    0.850850
9                       Age    -0.206330    0.813565
0                 Intercept    -0.209090    0.811322
14                     Pets    -0.321412    0.725124

A Feature is not particularly important:
-if its coefficient is around 0
-if its odds ratio is around 1

Hence, daily work load, distance to work, day of the week are not significant
