#### Import libraries

In [1]:
import numpy as np

## Scalers :

In [2]:
s = 5
s

5

## Vector:

In [4]:
#row vector
v=np.array([5,-2,4])
v

array([ 5, -2,  4])

## Matrices :

In [5]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types :

In [11]:
type(s)

int

In [12]:
type(v) #1-d array

numpy.ndarray

In [13]:
type(m) #2-d array 

numpy.ndarray

In [14]:
#scaler
s_array = np.array(5)
s_array

array(5)

In [15]:
type(s_array)

numpy.ndarray

## Data shapes :

In [21]:
#as s is int type and not a array object
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [24]:
#scaler is 0D object, hence no shape
s_array.shape

()

In [16]:
m.shape

(2, 3)

In [17]:
v.shape

(3,)

## Creating column vector :

In [19]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [20]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

## TENSORS :

In [25]:
m1 = np.array([[5,12,0],[-3,0,14]])
m1

array([[ 5, 12,  0],
       [-3,  0, 14]])

In [26]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [27]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  0],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

#### Tensor shape -

In [28]:
t.shape

(2, 2, 3)

## Addition :

In [29]:
m1+m2

array([[14, 20,  7],
       [-2,  3,  9]])

#### Exception (with scaler) :

In [31]:
m1+1

array([[ 6, 13,  1],
       [-2,  1, 15]])

## Subtraction :

In [30]:
m1-m2

array([[-4,  4, -7],
       [-4, -3, 19]])

## VECTORS 

In [32]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [33]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [35]:
s_array.T

array(5)

In [36]:
x= np.array([1,2,3])
x.T

array([1, 2, 3])

## DOT PRODUCT 

In [37]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [38]:
np.dot(x,y)

-66

#### Scaler * scaler

In [39]:
np.dot(5,6)

30

#### Scaler * vector

In [40]:
x

array([ 2,  8, -4])

In [46]:
5*x

array([ 10,  40, -20])

#### Scaler * Matrix

In [47]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

#### Matrix * Matrix

In [48]:
B = np.array([[2,-1],[0,0],[3,0]])
B

array([[ 2, -1],
       [ 0,  0],
       [ 3,  0]])

In [49]:
np.dot(A,B)

array([[28, -5],
       [36,  3]])